"""Update frame table schema - add roll columns and scoring fields

Revision ID: ef73e0ba6ff3
Revises: 
Create Date: 2025-10-28 15:18:55.639069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef73e0ba6ff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        # Add new columns with default values first
        batch_op.add_column(sa.Column('roll1', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('roll2', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('roll3', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('frame_score', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('running_total', sa.Integer(), nullable=False, server_default='0'))
    
    # Copy existing score data to frame_score for existing records (outside batch operation)
    op.execute("UPDATE frame SET frame_score = score WHERE score IS NOT NULL")
    
    # Drop the old score column
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=False))
        batch_op.drop_column('running_total')
        batch_op.drop_column('frame_score')
        batch_op.drop_column('roll3')
        batch_op.drop_column('roll2')
        batch_op.drop_column('roll1')

    # ### end Alembic commands ###
